services:


  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    profiles:
      - media
      - books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    security_opt:
      - seccomp:unconfined #optional
    volumes:
      - type: bind
        source: config/media/calibre
        target: /config
      - ${MEDIA_PATH_1}:/data
      - ${MEDIA_PATH_2}/usenet/:/usenet2
    profiles:
      - media
    ports:
      - 9080:8080
      - 9181:8181
      - 9081:8081
    restart: unless-stopped

  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    profiles:
      - media
      - books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - type: bind
        source: config/media/calibre-web
        target: /config
      - ${MEDIA_PATH_1}:/data
    restart: unless-stopped
    profiles:
      - media
    depends_on:
      - calibre
    ports:
      - 8083:8083




  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    profiles:
      - media
      - streaming
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - VERSION=docker
    volumes:
      - type: bind
        source: config/media/plex
        target: /config
      - ${MEDIA_PATH_1}/media/tv:/tv
      - ${MEDIA_PATH_1}/media/movies:/movies
      - ${MEDIA_PATH_2}/media/tv:/tv2
      - ${MEDIA_PATH_2}/media/movies:/movies2
      - ${MEDIA_PATH_2}/media/pictures:/pictures2
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    profiles:
      - media
      - streaming
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - type: bind
        source: config/media/jellyfin
        target: /config
      - jellyfin-cache:/cache
      - type: bind
        source: ${MEDIA_PATH_1}/media
        target: /media
        read_only: true
      - type: bind
        source: ${MEDIA_PATH_2}/media
        target: /media2
        read_only: true
    restart: 'unless-stopped'

volumes:
  jellyfin-cache:
