include:
  - docker-compose-frigate.yml
  - docker-compose-media.yml
  - docker-compose-infra.yml
  - docker-compose-arr.yml
  - docker-compose-domotica.yml

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command:
      - --cleanup=true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


# Persistent data volumes
volumes:
  proxy-manager-data:
  portainer-data:
  influxdb-data:
  mosquitto-data:
