version: "3"

services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    profiles:
      - frigate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: config/frigate/config.yaml
        target: /config/config.yaml
      - frigate-storage:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frigate.rule=Host(`frigate.lan`)"
      - "traefik.http.routers.frigate.entrypoints=web"
volumes:
  frigate-storage:
