version: "3"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - type: bind
        source: config/sonarr
        target: /config
      - /media/external/TV:/tv
      - /media/external/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    profiles:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - type: bind
        source: config/radarr
        target: /config
      - /media/external/Movies:/movies
      - /media/external/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    profiles:
      - media

  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - type: bind
        source: config/nzbget
        target: /config
      - /media/external/Downloads:/downloads

    ports:
      - 6789:6789
    restart: unless-stopped
    profiles:
      - media
